include ENVIRONMENTS
GO=/usr/local/go/bin/go

.PHONY: build dist

all: build

build:
	GOOS=linux $(GO) build -o $(OUT) -ldflags "-s -w -X 'main.APPLICATION_VERSION=$(VERSION)'" ./cmd/protocol/.

dist: build
	tar czvf $(OUT)-$(VERSION)-linux-amd64.tar.gz $(OUT)

clean:
ifneq (,$(wildcard $(OUT)))
	@rm $(OUT)
endif

	@$(GO) clean

