include ENVIRONMENTS
GO=/usr/local/go/bin/go

.PHONY: build_linux 

all: build_linux

build_linux:
	GOOS=linux $(GO) build -o protocol -ldflags "-X 'main.APPLICATION_VERSION=$(VERSION)'" ./cmd/protocol/.

clean:
ifneq (,$(wildcard $(OUT)))
	@rm $(OUT)
endif

	@$(GO) clean
